diamondburned/arikawa

state/state_events.go
state/store.go
state/store_default.go
state/store_noop.go

Does exactly what the title says it does :)

Add VoiceState caching to the state package

---

utils/httputil/client.go

fix(api): no retries on error

---

api/emoji.go

API: fix #27

---

discord/invite.go

Discord: incomplete Invite type

---

api/guild.go
discord/guild.go
discord/guild_const.go

API: fix multiple issues with ModifyIntegration

---

api/guild.go

API: rename GuildImageType to GuildImageStyle

---

api/guild.go

API: GuildsRange query fields don't get omitted

---

api/guild.go
api/webhook.go

API: AttachIntegration has empty payload

---

api/emoji.go
api/message_reaction.go

API: Deprecate FormatEmojiAPI in favor of a simpler function

---

gateway/events.go
state/state_events.go

Gateway: fix missing inheritance

---

api/invite.go

API: split Invite into Invite and InviteWithCount

---

api/member.go

API: split Prune into Prune and PruneWithCount methods

---

api/webhook.go

API: Create GuildWebhooks and ChannelWebhooks method

---

api/message.go

 API: add SendMessage for a simple message

---

api/user.go

API: remove missing CreateGroup method comment

---

api/message.go

API: add EditText and EditEmbed methods

---

api/user.go

API: create missing UserConnections method

---

api/guild.go
discord/guild.go

API: Add missing GuildPreview endpoint 

---

discord/emoji.go
discord/guild.go
discord/url.go
discord/user.go

Discord: allow custom file extension for URL methods

---

api/guild.go
discord/guild.go

API: Switch from GuildEmbed to GuildWidget

---

state/state.go

State: Parallelize API requests in abstract functions

---

api/guild.go
api/member.go
api/message.go
api/message_reaction.go

API: lift limits for getters

---

api/guild.go

API: fix wrong endpoint for GuildWidget and ModifyGuildWidget

---

discord/invite.go

Discord: fix problems with the Invite struct

---

discord/auditlog.go

This PR adds/improves godocs of all types/functions/constants regarding audit logs.

Discord: add docs for auditlog.go

---

discord/guild.go
discord/guild_const.go

This PR adds the missing fields to the `Guild` struct and adds docs to all guild types.

Fix issues with Guild

---

api/invite.go

 APi: fix docs for DeleteInvite

---

utils/json/option/bool.go
utils/json/option/custom.go
utils/json/option/number.go
utils/json/option/string.go

Utils: fix issues with Nullable types

---

api/member.go

API: add IncludeRoles option for Prune

---

api/guild.go
api/member.go
api/message.go
api/message_reaction.go

This PR fixes errors with the automatic pagination that occur at 3+ requests.

Discord: fix invalid calc of after

---

api/message_reaction.go
discord/channel.go

Discord: typed IconURL for Channel

---

discord/guild.go

 Discord: Guild has no DiscorverySplashURL method

---

state/state.go

State: Make call to Channel in state.Message parallel

---

bot/ctx_call.go
bot/extras/infer/infer.go
bot/extras/middlewares/middlewares.go
discord/emoji.go
discord/message.go
discord/snowflake.go
discord/time.go
state/state.go
state/store.go
state/store_default.go
voice/session.go
voice/voicegateway/commands.go

v1: Discord: Rename Valid methods

---

README.md
_example/advanced_bot/bot.go
_example/advanced_bot/debug.go
api/api.go
api/channel.go
api/emoji.go
api/rate/rate.go
api/send.go
bot/arguments.go
bot/ctx.go
bot/ctx_call.go
bot/ctx_plumb_test.go
bot/ctx_test.go
bot/extras/arguments/mention_test.go
bot/extras/middlewares/middlewares_test.go
bot/extras/shellwords/shellwords.go
bot/subcommand.go
discord/user.go
gateway/gateway.go
gateway/op.go
gateway/ready.go
state/state.go
state/state_events.go
utils/wsutil/conn.go
utils/wsutil/op.go
voice/README.md

Linting and typo fixes
